pipeline
{
    agent {
        dockerfile{ label 'zip-job-docker' }
    }

    environment {
        ARTIFACT_FOLDER_VERSION = '1.2.0'
    }

    stages 
    {
        stage ('Git')
        {
            steps
            {
                git branch: 'main', url: 'https://github.com/shvartz311/docker-jenkins-artifactory.git'
            }
        }
        stage ('Artifactory Configuration')
        {
            steps
            {
                rtServer (id: SERVER_ID,  url: "http://172.18.0.2:8082/artifactory", username: 'admin', password: 'password')
            }
        }
        stage('Build stage - Run script')
        {
            steps
            {
                script
                {          
                    sh "python3 /tmp/zip_job.py"
                }
            }
        }
        stage ('Publish stage - Archive artifacts')
        {
            steps
            {
                rtUpload (
                    serverId: SERVER_ID,
                    spec: '''{
                        "files": [
                        {
                            "pattern": "/var/jenkins_home/workspace/test-pipeline/*.zip",
                            "target": "binary-storage/${ARTIFACT_FOLDER_VERSION}/"
                        }
                    ]
                }''',
                failNoOp: true)
            }
        }
        stage('Report stage - Send e-mail')
        {
            steps
            {
                emailext body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}\n More info at: ${env.BUILD_URL}",
                recipientProviders: [buildUser()],
                subject: "Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
                to: 'oryshkat@hotmail.com'
            }
        }
        stage('Cleanup - delete workspace')
        {
            steps
            {
                always {cleanWs()}
            }
        }
}
}